app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('autenticacion.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
]

app/cart/models.py
from django.db import models

# Create your models here.

app/cart/views.py
from django.shortcuts import redirect
from products.models import Product
from django.contrib.auth.decorators import login_required
from .cart import Cart


@login_required(login_url="/autenticacion/login")
def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def remove_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.remove(product)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def decrement_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.decrement(product=product)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("listado_productos")

app/templates/cart/widget.html
{% load cart_tags %}
<table class="table table-bordered">
     <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carrito de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
           {% for key, value in request.session.cart.items %}
                <tr class="text-center">
                    <td>{{ value.name }}</td>
                    <td>{{ value.quantity }}</td>
                    <td>
                        <a
                            href="{% url 'cart:add_product' value.product_id %}"
                            class="btn btn-sm btn-success"
                        >
                            +
                        </a>
                        <a
                            href="{% url 'cart:decrement_product' value.product_id %}"
                            class="ml-2 btn-sm btn btn-danger"
                        >
                            -
                        </a>
                        Total {{ value.price|multiply:value.quantity|money_format:"$" }}
                    </td>
                </tr>
           {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No tienes productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ cart_total_amount|money_format:"$" }}
            </td>
        </tr>
        {% if request.session.cart.items %}
            <tr>
                <td colspan="3">
                    <a href="{% url "process_order" %}" class="btn btn-success">Crear pedido</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>
</table>